# Generated by Django 2.2.1 on 2019-05-23 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
